name: Swift build and test


on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]


jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        swift: ["5.8", "5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

  build:
    name: Swift 5.7 on macos-12
    runs-on: mocos-12
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.7
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

