name: Build documents


on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build SwiftADIF
        run: |
          swift package --allow-writing-to-directory ./docs \
          generate-documentation \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path SwiftADIF \
          --output-path ./docs
      - name: Build ADIParser
        run: |
          swift package --allow-writing-to-directory ./docs \
          generate-documentation \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path ADIParser \
          --output-path ./docs
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
